# Generated by Django 3.0.3 on 2020-11-22 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('make', models.CharField(max_length=64, verbose_name='make')),
                ('model', models.CharField(max_length=64, verbose_name='model')),
            ],
            options={
                'unique_together': {('make', 'model')},
            },
        ),
    ]
