# Generated by Django 3.1.3 on 2020-11-19 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='make',
            field=models.CharField(max_length=64, verbose_name='make'),
        ),
    ]
